### ISSUE TITLE
Autor cytatu

### ISSUE THREAD

**Issue by qwercik** [php-kurs/php-kurs#3]
Możecie sprecyzować autora cytatu "Wybudowałem pomnik trwalszy niż ze spiżu" - był to Horacy :)

**Comment by efiku** [comment]
Chyba zmienimy trochę właśnie stronę tytułową ^^

> Stwierdziliśmy, że wiedzą trzeba się dzielić. Jak to pisali starożytni Rzymianie "Exegi monumentum aere perennius" - wzniosłem pomnik trwalszy niż ze spiżu. Bo właśnie wiedza jest tym, co po nas pozostanie. Uważamy, że dostęp do interesującej nas wiedzy powinien być darmowy.
> Zarówno ja @efiku jak i @event15 jesteśmy wyznawcami idei Open Source.
> Ale niestety nie jesteśmy bajkopisarzami i nie potrafimy wymyślić lepszego wstępu. Zachęcamy jednak do przejrzenia tego, co mamy do zaoferowania.

Trzeba by było to jakoś lepiej napisać. @qwercik  Masz jakiś pomysł?

**Comment by qwercik** [comment]
Nie wiem, polonista ze mnie jak z koziej du*y trąba xD
Jutro coś może wymyślę.

**Comment by efiku** [comment]
Długo coś myślisz ;)

**Comment by qwercik** [comment]
Haha :) No zapomniałem, widzisz. Jak nie zapomnę to pomyślę ;)
