### ISSUE TITLE
Zmiana wersji PHP

### ISSUE THREAD

**Issue by efiku** [php-kurs/php-kurs#6]
> Stworzone na podstawie wersji PHP 5.6+ oraz zbioru osobistych doświadczeń.

Sugeruję zamienić na:

Stworzone na podstawie wersji **PHP 7.0+** oraz zbioru osobistych doświadczeń.

**Comment by event15** [comment]
5.6 jeszcze żyje a nie wszystkie hostingi mają pełne wsparcie. 
Można zrobić "wersji PHP 5.6+, z naciskiem na najnowsze rozwiązania, które oferuje nam PHP 7.0+ oraz zbioru osobistych doświadczeń."
Albo coś na ten styl. A jak już nie będzie żadnego dobrego zamiennika dla tego zdania, to w sumie 7.0+ może być :)

**Comment by efiku** [comment]
Dobra lecimy dalej ;)
